name: Release k8s-ssh-bastion chart

on:
  push:
    tags:
      - '*'

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Configure Git
        run: |
          git config user.name "$GITHUB_ACTOR"
          git config user.email "$GITHUB_ACTOR@users.noreply.github.com"

      - name: Install Helm
        uses: azure/setup-helm@v4.3.0

      - name: Chart | Push
        uses: appany/helm-oci-chart-releaser@v0.4.2
        with:
          name: k8s-ssh-bastion
          repository: neptune-software/charts
          registry: ghcr.io
          registry_username: ${{ github.actor }}
          registry_password: ${{ secrets.GITHUB_TOKEN}}
          tag: ${{ github.ref_name }}
          app_version: ${{ github.ref_name }}
