name: Release k8s-ssh-bastion chart

on:
  push:
    branches:
      - main
    tags:
      - '*'

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Configure Git
        run: |
          git config user.name "$GITHUB_ACTOR"
          git config user.email "$GITHUB_ACTOR@users.noreply.github.com"

      - name: Install Helm
        uses: azure/setup-helm@v4.3.0

      - name: Push Helm chart to OCI compatible registry (Github)
        uses: bsord/helm-push@4.2.0
        with:
          useOCIRegistry: true
          registry-url:  oci://ghcr.io/${{ github.repository }}/charts
          username: ${{ github.actor }}
          access-token: ${{ secrets.REGISTRY_ACCESS_TOKEN }}
          force: true
          chart-folder: charts/k8s-ssh-bastion
